### ISSUE TITLE
Inclusion in 'providers' array breaks artisan

### ISSUE THREAD

**Issue by Deacs** [nWidart/DbExporter#23]
After adding _'Nwidart\DbExporter\DbExportHandlerServiceProvider'_ to the 'providers' array in config/app.php, any call to _php artisan [any existing command]_ returns _' [BadMethodCallException] Call to undefined method [package]'_

If the reference to the ServiceProvider is removed, artisan functions as expected.

Installation guide has been followed to the letter although I am running Laravel 5.1. Had to use dev-master as 1.0 would not install.

If I comment out _$this->package('nwidart/db-exporter');_ from the _boot()_ method in #27 of _DbExportHandlerServiceProvider.php_, artisan is functional but •php artisan dbe:seeds• throws _PHP Fatal error:  Class 'Str' not found in /base/myapp/vendor/nwidart/db-exporter/src/Nwidart/DbExporter/DbSeeding.php on line 112_

Obviously happy to provide any further details that would help.

**Comment by qnorsten** [comment]
I had the same problem. Just started learning Laravel a few weeks ago. Seems like they changed something in Laravel 5 quite newly. 
I managed to solve the problem by commenting out the mentioned row in the previous comment and by 
adding this row to my aliases array in config/app.php
Str'             => 'Illuminate\Support\Str',

**Comment by anaxamaxan** [comment]
See #30 for a workaround.

**Comment by Deacs** [comment]
Apologies, just seen the workaround reply. Thanks for responding
