### ISSUE TITLE
[BadMethodCallException] Call to undefined method [package]

### ISSUE THREAD

**Issue by Chopsueyer** [nWidart/DbExporter#26]
Hi!

I can't use your the package correctly after install the dev-master version via composer. I always get this error if I try to use it directly or if I try to do your "publish" command ("php artisan config:publish nwidart/db-exporter"):

    [BadMethodCallException]            
    Call to undefined method [package]
    

Any idea to help me?

Thanks

**Comment by nWidart** [comment]
Duplicate of #25
