### ISSUE TITLE
 Class 'Str' not found in src/Nwidart/DbExporter/DbMigrations.php on line 217

### ISSUE THREAD

**Issue by ryh** [nWidart/DbExporter#32]
Class 'Str' not found in [src/Nwidart/DbExporter/DbMigrations.php#L217](https://github.com/nWidart/DbExporter/blob/master/src/Nwidart/DbExporter/DbMigrations.php#L217)

fix:full namespace use

``` php
use Illuminate\Support\Str;
```

**Comment by joshbrw** [comment]
You can fix this by adding a `Str` alias in your `config/app.php`

**Comment by damourcode** [comment]
this can work in your blade
 {!!  \Illuminate\Support\Str::words($string->body, 10) !!}
