### ISSUE TITLE
Call to undefined method Nwidart\DbExporter\DbExportHandlerServiceProvider::package()

### ISSUE THREAD

**Issue by logig** [nWidart/DbExporter#44]
### I'm sorry to say that the problem still exists, even the latest version.

![image](https://cloud.githubusercontent.com/assets/15779888/21951680/39e3d1e0-da45-11e6-8833-21c4c809ddb7.png)
--------------------
![image](https://cloud.githubusercontent.com/assets/15779888/21951681/4bcdac32-da45-11e6-87bc-28e2a6801e46.png)

**Comment by weezqyd** [comment]
i would recommend you  to use this package [https://github.com/Elimuswift/db-exporter]( https://github.com/Elimuswift/db-exporter) i added a couple of features and updated it to use the latest version of laravel.

**Comment by logig** [comment]
Great work! Thanks a lot!
